package fixed2free.integration;

public interface DeviceFileInfoProvider {
//	FLDL0100 List Data Section
//
//	Offset	Type	Field
//	Dec	Hex
//	0	0	CHAR(10)	Field name
	
//	10	A	CHAR(1)	Data type
//	11	B	CHAR(1)	Use
//	12	C	BINARY(4)	Output buffer position
//	16	10	BINARY(4)	Input buffer position
//	20	14	BINARY(4)	Field length in bytes
//	24	18	BINARY(4)	Digits
//	28	1C	BINARY(4)	Decimal position
//	32	20	CHAR(50)	Field text description
//	82	52	CHAR(2)	Edit code
//	84	54	BINARY(4)	Edit word length
//	88	58	CHAR(64)	Edit word
//	152	98	CHAR(20)	Column heading 1
//	172	AC	CHAR(20)	Column heading 2
//	192	C0	CHAR(20)	Column heading 3
//	212	D4	CHAR(10)	Internal field name
//	222	DE	CHAR(30)	Alternative field name
//	252	FC	BINARY(4)	Length of alternative field name
//	256	100	BINARY(4)	Number of DBCS characters
//	260	104	CHAR(1)	Null values allowed
//	261	105	CHAR(1)	Host variable indicator
//	262	106	CHAR(4)	Date and time format
//	266	10A	CHAR(1)	Date and time separator
//	267	10B	CHAR(1)	Variable length field indicator (overlay for MI mapping)
//	268	10C	BINARY(4)	Field text description CCSID
//	272	110	BINARY(4)	Field data CCSID
//	276	114	BINARY(4)	Field column headings CCSID
//	280	118	BINARY(4)	Field edit words CCSID
//	284	11C	BINARY(4)	UCS-2 displayed field length
//	288	120	BINARY(4)	Field data encoding scheme
//	292	124	BINARY(4)	Maximum large object field length
//	296	128	BINARY(4)	Pad length for large object
//	300	12C	BINARY(4)	Length of user-defined type name
//	304	130	CHAR(128)	User-defined type name
//	432	1B0	CHAR(10)	User-defined type library name
//	442	1BA	CHAR(1)	Datalink link control
//	443	1BB	CHAR(1)	Datalink integrity
//	444	1BC	CHAR(1)	Datalink read permission
//	445	1BD	CHAR(1)	Datalink write permission
//	446	1BE	CHAR(1)	Datalink recovery
//	447	1BF	CHAR(1)	Datalink unlink control
//	448	1C0	BINARY(4)	Display or print row number
//	452	1C4	BINARY(4)	Display or print column number
//	456	1C8	CHAR(1)	ROWID column
//	457	1C9	CHAR(1)	Identity column
//	458	1CA	CHAR(1)	GENERATED BY
//	459	1CB	CHAR(1)	Identity column - CYCLE
//	460	1CC	DECIMAL(31,0)	Identity column - Original START WITH
//	476	1DC	DECIMAL(31,0)	Identity column - Current START WITH
//	492	1EC	BINARY(4)	Identity column - INCREMENT BY
//	496	1F0	DECIMAL(31,0)	Identity column - MINVALUE
//	512	200	DECIMAL(31,0)	Identity column - MAXVALUE
//	528	210	BINARY(4)	Identity column - CACHE
//	532	214	CHAR(1)	Identity column - ORDER
//	533	215	CHAR(1)	Implicitly hidden
//	534	216	CHAR(1)	Row change timestamp GENERATED
//	535	217	CHAR(10)	Field Procedure program name
//	545	221	CHAR(10)	Field Procedure library name
//	Start of change555	22B	BINARY(2)	Timestamp precision
//	557	22D	CHAR(3)End of change	Reserved
//
//
//	FLDL0200 List Data Section
//
//	dir
//	Offset	Type	Field
//	Dec	Hex
//	0	0	BINARY(4)	Length of FLDL0200 format
//	4	4	BINARY(4)	Displacement to default value
//	8	8	BINARY(4)	Length of default value
//	12	C		All fields defined by FLDL0100 format
//	*	*	CHAR(*)	Default value
//
//
//	FLDL0300 List Data Section
//
//	Offset	Type	Field
//	Dec	Hex
//	0	0	BINARY(4)	Length of FLDL0300 format
//	4	4	BINARY(4)	Displacement to all fields defined by FLDL0100 format
//	8	8	BINARY(4)	Displacement to alternative field name
//	12	C	BINARY(4)	Displacement to default value
//	16	10	BINARY(4)	Length of default value
//	*	*	 	All fields defined by FLDL0100 format
//	*	*	CHAR(*)	Alternative field name (long)
//	*	*	CHAR(*)	Default value




}
